### ISSUE TITLE
[Discovery] Use CE term "producer" instead of "provider"

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#620]
Let's try to reuse the same terms as CE.

**Comment by duglin** [comment]
> The second case becomes relevant if multiple providers support the same event types. Use case 1 is likely the dominant use case. Given the example of a public cloud provider where all producers produce events, there might be dozens of sources (producer systems) and hundreds of event types. The discovery funnel of producer first, then event types helps users navigate without having to see large lists of event types. Both of these cases show the importance of using filters in the discovery API to narrow down the selection of available events.

I wonder if this distinction between "provider" and "producer" is a good one to make. Would it make more sense to have a model where there's just one "producer" but then there are many "sources"? The difference between sources could be smallish, e.g. different "buckets" in an object storage, or it could be large, e.g. two totally different/unrelated backend systems?

In the end, when an event arrives at the consumer, all they will see is the CE metadata and we don't have different attributes for these two concepts - we seem to merge them into "source". So if a consumer can distinguish between the two concepts from a CE message, can they do so when using Discovery too?

**Comment by deissnerk** [comment]
The original idea of producer was just another one. It's the *thing* that actually brings the event onto the wire. I understood the *provider* more as a *class* or *type* of source. The problem of *source* is that it can be anything, and it is not guaranteed to enumerable.

**Comment by duglin** [comment]
Yup - I'm just trying to find a way to simplify the model and if there's something in the Discovery query output that never shows up in the event.... I kind of wonder if we really need it.  Or put it another way... if there are multiple providers sending to a consumer, how does the consumer know how to differentiate them? Do they need to?  It seems the same solution/answer should be used for the consumer of the event as the entity querying the Discovery API.

**Comment by duglin** [comment]
Thinking more about this... maybe my concern would be lessened if "Provider" wasn't a first class entity, but instead it was just an extra bit of metadata on a "Source", and "Source" was the top level entity.

I'm struggling with this section: https://github.com/cloudevents/spec/blob/541e790ef8076f889adfe7a82859f815ec80d22c/discovery.md#entities-in-the-api
and trying to correlate it to the CEs the consumer will get and with the Discovery API - but then also consider how a UI might look.  Forgive the rambling...

What if the query results looked something like this:
```
- sources
  - source: https://github.com/      # prefix of ce-source attribute value
    - name: GitHub Repository        # Today's "Provider", good for UI, mutable
    - types
      - type: com.github.push        # ce-type value
        name: Push Event             # Human readable one-liner, good for UI, mutable
        ...                          # other metadata - e.g. dataschema
      - type: com.github.fork
      ...
  - source: https://github.bigco.com/
    - name: BigCo's github instance
    - types:
      - type: org.github.push
      ...
```
Note: the "mutable" comment is something kind of important. We have to allow for typos or name changes w/o breaking existing queries. Which means (for the most part) queries should be based on non-human-readable info. Not to say we can't allow people to search over human strings, but that's not as reliable.

Then a machine can reliable do:

`...?source=https://github.com`
to see all of `GitHub Repository`'s event types.

`...?type=com.github.push`
will return all `sources` that support this type of event (which is `https://github.com` and `https://github.bigco.com`)

For the most part, this reduces things down to just "source" and "type", with "source" being the owner/scope of "type". Everything else becomes metadata about those two entities.

**Comment by deissnerk** [comment]
I think this relates to #609. As the name of the event provider is essentially used as a key, it confuses me that it's supposed to be human readable. 
@duglin I think your example is really helpful, but the sources you put in there are not realistic. Wouldn't it be something like `https://github.com/{org}/{repo}`? This is what makes it hard to use in queries. @mikehelmick had something like a source pattern in one of his earlier proposals. I think that is a good idea, but it's not really usable for queries. It would be great to have something to group sources and give a name to these patterns. You can call it _provider_ or _source class_. We intentionally kept `source` completely open. If we had some structure for `source`, maybe even a URI scheme similar to what projects like SPIFFE have, we could make use of that. 
I also find it unfortunate that the _producer_ is in the center of this. To me it was always just some technical entity.

**Comment by duglin** [comment]
I was hoping to avoid templates, but maybe we can't if we really want machine processable stuff.
One option would be to do this:
```
- source: https://github.com
  name: GitHub Repository
  ce-source: https://github.com/{org}/{repo}
  type:
  - ...
```
I suppose `source` in this context might be what @mikehelmick was calling `provider`, and I guess this might be confusing to use `source` in different ways, but I think using `source` or `discovery-source` or `source-prefix` or `source-class`.... would better than a totally new term.
